apiVersion: k8s.nginx.org/v1alpha1
kind: GlobalConfiguration 
metadata:
  name: {{ include "common.name" . }}-global-configuration
  namespace: {{ include "common.namespace" . }}
spec:
  listeners:
  - name: opensync-gw-controller-port-listener
    port: 6640
    protocol: TCP
  - name: opensync-gw-redirector-port-listener
    port: 6643
    protocol: TCP
  - name: opensync-mqtt-port-listener
    port: 1883
    protocol: TCP